#+TITLE: FP in PHP
#+REVEAL_THEME: night
#+OPTIONS: toc:1, num:nil, f:t
#+REVEAL_ROOT: file:///home/tim/workspace/javascript/reveal.js

* Null: Worst Language Feature Ever

** The Faces of Null
- PHP: Fatal Error: Call to a member function [...] on a non-object
- Java: java.lang.NullPointerException
- C#: System.NullReferenceException: Object reference not set to an instance of an object.
- Javascript:
  - "undefined is not a function."
  - "Cannot read property 'x' of null."
- Python: AttributeError: 'NoneType' object has no attribute 'xxx'
- Ruby: undefined method '...' for nil:NilClass
- C/C++: segmentation fault

** Why is null so bad?
- It's use makes for poor APIs
- It adds this extra value to every type but does not honor any of their contracts.

Null is the value that has no value.

** Hoare's Billion Dollar Mistake
"I call it my billion-dollar mistake. It was the invention of the null reference in 1965. At that time, I was designing the first comprehensive type system for references in an object oriented language (ALGOL W). My goal was to ensure that all use of references should be absolutely safe, with checking performed automatically by the compiler. But I couldn't resist the temptation to put in a null reference, simply because it was so easy to implement. This has led to innumerable errors, vulnerabilities, and system crashes, which have probably caused a billion dollars of pain and damage in the last forty years."[fn:: https://en.wikipedia.org/wiki/Tony_Hoare#Apologies_and_retractions]

-- Tony Hoare; ACM Turing Award recipient, inventor of quicksort and the null reference

** You don't actually need the concept of null
Some languages don't even have it:
- Haskell
- Rust
- ML-family languages
- Flow
- Other languages?

** So why do languages have it?
- It's almost always used to represent the lack of a value.
- Sometimes you need to declare a variable before you can assign it a value.



* Is There an Alternative? Maybe

** Solution 1: Pretend it doesn't exist
- Never return null. Never accept null as parameter.[fn:: http://c2.com/cgi/wiki?NoNullBeyondMethodScope]

** Solution 2: Use the [[https://en.wikipedia.org/wiki/Null_Object_pattern][Null Object pattern]]
- Create a type that you can return instead of null that has some neutral behavior.
- But it's often not applicable.

** Solution 3: Use an Option/Maybe type
- Haskell has Maybe
- Java 8 has Optional
- Scala has Option
- C++ has an optional template class in a proposed extension
- Swift has Optional
- Ruby has [[https://github.com/rap1ds/ruby-possibly][Possibly]] (library)

** What is Option/Maybe?
It's a type with two possible values: Nothing and Just (or None and Some)
- Nothing represents no value
- Just contains a value

** In Haskell
#+BEGIN_SRC haskell
data Maybe a = Just a
             | Nothing
#+END_SRC

** In OO
But in an OO language you need to "simulate" it like so:
#+BEGIN_SRC php
abstract class Maybe {}

class Just extends Maybe {
   private $val;

   public function __construct($val) { $this->val = $val; }
}

class Nothing extends Maybe {}
#+END_SRC

** Class Hierarchy
(show image of class hierarchy)

** An Example
Suppose you have a software model of a computer system and you want to get the firmware version of the USB controller for the computer's soundcard. You'd like to write code that looks like this:
#+BEGIN_SRC php
$version = $computer->getSoundcard()->getUSB()->getVersion();
#+END_SRC

** An Example, Continued
But not all computers have soundcards and not all soundcards have a USB controller and in this model their absence is represented by returning null, so you'd have to write

#+BEGIN_SRC php
$version = "UNKNOWN";
$soundcard = $computer->getSoundcard();
if ($soundcard != null) {
   $usb = $soundcard->getUSB();
   if ($usb != null) {
      $version = $usb->getVersion();
   }
}
#+END_SRC

And now you're in "The Pyramid of Doom"!

** An Example, using Maybe, First Attempt
Here we change the return type of getSoundcard() and getUSB() to Maybe

#+BEGIN_SRC php
$version = "UNKNOWN";
$maybeSoundcard = $computer->getSoundcard();
if (!$maybeSoundcard->isNothing()) {
   $soundcard = $maybeSoundcard->get();
   $maybeUSB = $soundcard->getUSB();
   if (!$maybeUSB->isNothing()) {
      $usb = $maybeUSB->get();
      $version = $usb->getVersion();
   }
}
#+END_SRC

But this is worse than before!

** An Example, using Maybe, Second Attempt
Use `map` and `flatMap` instead:

#+BEGIN_SRC php
$version = "UNKNOWN";
$maybeSoundcard = $computer->getSoundcard();
$maybeUSB = $maybeSoundcard->flatMap(function ($soundcard) {
   return $soundcard->getUSB();
});
$maybeVersion = $maybeUSB->map(function ($usb) {
   return $usb->getVersion();
});
if (!$maybeVersion->isNothing()) {
   $version = $maybeVersion->get();
}
#+END_SRC

** An Example, using Maybe, Second Attempt, cleaned up
#+BEGIN_SRC php
$maybeSoundcard = $computer->getSoundcard();
$maybeUSB = $maybeSoundcard->flatMap(function ($soundcard) {
   return $soundcard->getUSB();
});
$maybeVersion = $maybeUSB->map(function ($usb) {
   return $usb->getVersion();
});
$version = $maybeVersion->getOrElse("UNKNOWN");
#+END_SRC

** An Example, using Maybe, Second Attempt, Single Assignment
#+BEGIN_SRC php
$version = $computer->getSoundcard()
                    ->flatMap(function ($soundcard) {
                                 return $soundcard->getUSB();
                              })
                    ->map(function ($usb) {
                              return $usb->getVersion();
                          })
                    ->getOrElse("UNKNOWN");
#+END_SRC

** An Example, In Haskell
#+BEGIN_SRC haskell
data Computer = Computer { getSoundcard :: Maybe Soundcard }
data Soundcard = Soundcard { getUSB :: Maybe USB }
data USB = USB { getVersion :: String }

computer = undefined :: Computer

version = fromMaybe "UNKNOWN" (getSoundcard computer >>= getUSB >>= return . getVersion)
#+END_SRC

** We can clean up the PHP by first defining the anonymous functions:
#+BEGIN_SRC php
$getUsb = function ($soundcard) { return $soundcard->getUSB(); }
$getVersion = function ($usb) { return $usb->getVersion(); }

$version = $computer->getSoundcard()
                    ->flatMap($getUsb)
                    ->map($getVersion)
                    ->getOrElse("UNKNOWN");
#+END_SRC



* The Problem with Exceptions

** Exceptions are a Problem Because . . .
- Throwing is a side effect
- They are impure
- They make functions/methods partial
- Unchecked exceptions are not a part of a function's/method's contract
- Exception handling requires a lot of boilerplate
- They are costly to handle
- They can put data into a "bad" state
- Exceptions are typically used for control flow



* A Solution to the Exception Problem

** Value-based Error Signaling
- Use a type that has two possible values: one that signals an error, the other success.
- functional-php library uses "Either", a generic type with two possible values: "Left" and "Right", each of which can hold values of different types.
  - "Left" means error and typically contains an error string
  - "Right" means success and holds the value of interest (just like "Just"!)

** Class Hierarchy
(show image of Either class hierarchy)

** Example
#+BEGIN_SRC php
$data = 'A bit of data.';
$eitherFile = open('/path/to/some/file.txt', 'rw');
$eitherFile = $eitherFile->flatMap(function ($file) use ($data) {
   return write($file, $data);
})
#+END_SRC

** Another Example
#+BEGIN_SRC php
$eitherDiv = divide(1, 0);
#+END_SRC


* Let Me Out!

** So What Do I Do With This Maybe/Either?
#+ATTR_REVEAL: :frag roll-in
What if you have an Either but need to return an HTTP response? You could do something like:

#+ATTR_REVEAL: :frag roll-in
#+BEGIN_SRC php
public function someControllerMethod(...) {

   $eitherData = $this->someObject->getSomeImportantData(...);

   if ($eitherData->isLeft()) {
      $response = response($eitherData->get(), 400);
   } else {
      $response = response($eitherData->get(), 200);
   }

   return $response;
}
#+END_SRC

#+ATTR_REVEAL: :frag roll-in
But this isn't very "OO".

** You Could Add an Abstract Method to Either

#+BEGIN_SRC php
abstract class Either {

   ...

   abstract function toLaravelResponse();
}

class Left extends Either {

   ...

   function toLaravelResponse() {
      return response($this->val, 400);
   }
}

class Right extends Either {

   ...

   function toLaravelResponse() {
      return response(someViewConversion($this->val), 200);
   }
}
#+END_SRC

** The OO Solution Is to Use the Visitor Pattern

A visitor for Either looks like this:

#+BEGIN_SRC php
interface EitherVisitor {

   function visitLeft($left);

   function visitRight($right);
}
#+END_SRC

** Implementation of Visitor Pattern for Either

#+BEGIN_SRC php
abstract class Either {

   ...

   abstract function accept($visitor);
}

class Left extends Either {

   ...

   function accept($visitor) {
      return $visitor->visitLeft($this);
   }
}

class Right extends Either {

   ...

   function accept($visitor) {
      return $visitor->visitRight($this);
   }
}
#+END_SRC

** Conversion Example: Either to Laravel Response

#+BEGIN_SRC php
class EitherToLaravelResponse implements EitherVisitor {

   private $someView;

   function visitLeft($left) {
      return response($left->get(), 400);
   }

   function visitRight($right) {
      return response($this->someView($right->get()), 200);
   }
}

// and use it like so
$response = $eitherData->accept(new EitherToLaravelResponse());
#+END_SRC

** Conversion Example: Either to Maybe

#+BEGIN_SRC php
class EitherToMaybe implements EitherVisitor {

   function visitLeft($left) {
      return Maybe::nothing();
   }

   function visitRight($right) {
      return Maybe::fromValue($right);
   }
}

// and use it like so
$maybeData = $eitherData->accept(new EitherToMaybe());
#+END_SRC

** Too Much Work!
Sometimes it's just easier to abandon OO purity and do something like this:

#+BEGIN_SRC php
// convert Either to Laravel response
$response = $eitherData->isLeft() ?
            response($eitherData->get(), 400) :
            response(someView($eitherData->get()), 200);

// convert Either to Maybe
$maybeData = $eitherData->isLeft() ?
             Maybe::nothing() :
             Maybe::fromValue($eitherData->get());
#+END_SRC
